# Generated by Django 5.1.6 on 2025-03-27 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='location',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='title',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='emergency',
            name='emergency_type',
            field=models.CharField(choices=[('health', 'Health Emergency'), ('security', 'Security Emergency'), ('fire', 'Fire Emergency')], default='health', max_length=20),
        ),
        migrations.AddField(
            model_name='emergency',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('low', 'Low')], default='high', max_length=20),
        ),
        migrations.AddField(
            model_name='emergency',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='reported', max_length=20),
        ),
    ]
